import type { Metadata } from "next";
import { Urbanist, Lobster_Two } from "next/font/google";

import "./globals.css";
import { cn } from "@/lib/utils";

const urbanist = Urbanist({ subsets: ["latin"], variable: "--font-urbanist", });
const lobster = Lobster_Two({ weight: "400", subsets: ["latin"], variable: "--font-lobster", });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: ["/images/favicon.png"]
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html
      lang="en"
      className={cn(
        "h-full antialiased",
        urbanist.variable,
        lobster.variable
      )}
    >
      <body className="min-h-screen">{children}</body>
    </html>
  );
}